apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secrets-demo

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secretproviderclass.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: secrets-demo
  env: dev
