apiVersion: v1
kind: Service
metadata:
  name: secrets-demo
  namespace: secrets-demo
spec:
  selector:
    app: secrets-demo
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP
