apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secretproviderclass.yaml
  - pv.yaml
  - pvc.yaml
  - statefulset.yaml
  - service.yaml
  - postgres-exporter-config.yaml
  - servicemonitor.yaml

commonLabels:
  app: postgres
  env: dev
