apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - role.yaml
  - clusterrolebinding.yaml
  - rolebinding.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/name: cluster-autoscaler
  app.kubernetes.io/component: autoscaling
