apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend-api

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/name: backend-api
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: demo-platform
