apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-alb

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - pdb.yaml
  # Add image validation hook (uncomment to enable)
  - image-validation-hook-secure.yaml

commonLabels:
  app: nginx-alb
