apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-alb

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - nginx-config.yaml
  - pdb.yaml
  - servicemonitor.yaml

commonLabels:
  app: nginx-alb
