apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx-alb
spec:
  selector:
    app: nginx-alb
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 9113
      targetPort: 9113
      protocol: TCP
      name: metrics
  type: NodePort
